### ISSUE TITLE
Path to install_script.ps1

### ISSUE THREAD

**Issue by slanoe** [ViRGIS-Team/CondaExtensions#4]
Hello,
The extension doesn't install gdal-csharp for me. It doesn't reach the file install_script.ps1. 

```
install_script.ps1 : Le terme �install_script.ps1� n'est pas reconnu comme nom d'applet de commande, fonction, fichier 
de script ou programme ex�cutable. V�rifiez l'orthographe du nom, ou si un chemin d'acc�s existe, v�rifiez que le 
chemin d'acc�s est correct et r�essayez.
Au caract�re Ligne:1 : 1
+ install_script.ps1 -install gdal-csharp=1.1.1 -destination 'D:/projec ...
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (install_script.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I launch the command line with the relative path of install_script.ps1 from the root directory of my project and it works, I have directories Assets/Conda and Assets/StreamingAssets:

```
powershell Library/PackageCache/com.virgis.gdal\@3.4.100/Editor/Plugins/install_script.ps1 -install gdal-csharp=1.1.1 -destination 'D:\projects\my-project\Assets\Conda' -shared_assets 'D:\projects\my-project\Assets\StreamingAssets'
```
Did I make a mistake?

**Comment by runette** [comment]
I am trying to understand the background to the first error message - when do you get this message? It looks like there should be more to the error message with the Unity Editor details about when it was called?

Do you have the full error log?
